app:
  timezone: "Asia/Ho_Chi_Minh"
  mode: "BACKTEST"

data:
  source: "MT5_CACHE"
  timeframe: "M15"
  start: "2024-01-01"
  end: "2024-12-31"

account:
  initial_balance: 1000

sessions:
  asia:
    start: "06:00"
    end: "13:50"
  london:
    start: "14:00"
    end: "17:30"
  block_us:
    start: "18:00"
    end: "23:59"

risk:
  risk_per_trade_pct: 0.5
  max_daily_loss_pct: 1.5
  max_trades_per_day: 3

fill_model:
  spread_mode: "FIXED"
  fixed_spread_points: 30
  slippage_mode: "OFF"
